import * as fs from 'fs';
import { parseContractSpec, getSampleSpecEntries, ParsedContractSpec } from './193-soroban-contract-interface';

export interface ClientGeneratorParams {
  contractId?: string;
  specData?: any[];
  outputFilePath?: string;
  jsonOutput?: boolean;
}

/**
 * Maps a Soroban spec type string to a TypeScript type annotation.
 */
export function generateTsType(typeStr: string): string {
  if (!typeStr) return 'any';
  const t = typeStr.toLowerCase();

  if (t === 'bool') return 'boolean';
  if (t === 'u32' || t === 'i32') return 'number';
  if (t === 'u64' || t === 'i64' || t === 'u128' || t === 'i128' || t === 'u256' || t === 'i256') return 'bigint';
  if (t === 'string' || t === 'symbol' || t === 'address') return 'string';
  if (t === 'bytes') return 'Buffer';
  if (t === 'void') return 'void';

  if (t.startsWith('option<')) {
    const inner = typeStr.slice(7, -1);
    return `${generateTsType(inner)} | undefined`;
  }
  if (t.startsWith('vec<')) {
    const inner = typeStr.slice(4, -1);
    return `${generateTsType(inner)}[]`;
  }
  if (t.startsWith('map<')) {
    return 'Record<string, any>';
  }

  // Custom user-defined type name
  return typeStr;
}

/**
 * Generates an ScVal encoding expression for a parameter.
 */
export function generateScValEncoder(argName: string, typeStr: string): string {
  const t = typeStr.toLowerCase();

  if (t === 'bool') return `xdr.ScVal.scvBool(args.${argName})`;
  if (t === 'u32') return `xdr.ScVal.scvU32(args.${argName})`;
  if (t === 'i32') return `xdr.ScVal.scvI32(args.${argName})`;
  if (t === 'symbol') return `xdr.ScVal.scvSymbol(args.${argName})`;
  if (t === 'string') return `xdr.ScVal.scvString(args.${argName})`;
  if (t === 'address') return `new Address(args.${argName}).toScVal()`;

  return `xdr.ScVal.scvSymbol(String(args.${argName}))`;
}

/**
 * Generates an ScVal decoding expression for a return value.
 */
export function generateScValDecoder(typeStr: string): string {
  const t = typeStr.toLowerCase();

  if (t === 'bool') return 'scVal.b()';
  if (t === 'u32') return 'scVal.u32()';
  if (t === 'i32') return 'scVal.i32()';
  if (t === 'symbol' || t === 'string') return 'scVal.sym().toString()';
  if (t === 'address') return 'Address.fromScVal(scVal).toString()';

  return 'scVal';
}

/**
 * Generates TypeScript client wrapper code from a parsed specification.
 */
export function generateClientCode(spec: ParsedContractSpec, contractId: string): string {
  const lines: string[] = [];

  lines.push('// Auto-generated Soroban Contract Client');
  lines.push('// Generated by Stellar SDK Example Hub');
  lines.push('import { Contract, Operation, xdr, Address } from "@stellar/stellar-sdk";');
  lines.push('');

  // 1. Generate User-Defined Interfaces / Enums
  spec.structs.forEach((st) => {
    lines.push(`export interface ${st.name} {`);
    st.fields.forEach((f) => {
      lines.push(`  ${f.name}: ${generateTsType(f.type)};`);
    });
    lines.push('}');
    lines.push('');
  });

  spec.enums.forEach((en) => {
    lines.push(`export enum ${en.name} {`);
    en.cases.forEach((c) => {
      lines.push(`  ${c.name} = ${c.value},`);
    });
    lines.push('}');
    lines.push('');
  });

  // 2. Generate Client Class
  lines.push(`export class ContractClient {`);
  lines.push(`  public readonly contractId: string = "${contractId}";`);
  lines.push(`  private readonly contract: Contract;`);
  lines.push('');
  lines.push(`  constructor(contractId: string = "${contractId}") {`);
  lines.push(`    this.contractId = contractId;`);
  lines.push(`    this.contract = new Contract(contractId);`);
  lines.push(`  }`);
  lines.push('');

  // 3. Generate Method Helpers
  spec.functions.forEach((fn) => {
    const hasArgs = fn.inputs.length > 0;
    const argType = hasArgs
      ? `args: { ${fn.inputs.map((i) => `${i.name}: ${generateTsType(i.type)}`).join('; ')} }`
      : '';

    const returnTsType = fn.outputs.length > 0 ? generateTsType(fn.outputs[0]) : 'void';

    lines.push(`  /**`);
    lines.push(`   * Builds an unsigned Operation for calling function '${fn.name}'`);
    lines.push(`   */`);
    lines.push(`  public build${capitalize(fn.name)}Op(${argType}): xdr.Operation {`);

    if (hasArgs) {
      lines.push('    const scArgs: xdr.ScVal[] = [');
      fn.inputs.forEach((inp) => {
        lines.push(`      ${generateScValEncoder(inp.name, inp.type)},`);
      });
      lines.push('    ];');
      lines.push(`    return this.contract.call("${fn.name}", ...scArgs);`);
    } else {
      lines.push(`    return this.contract.call("${fn.name}");`);
    }

    lines.push(`  }`);
    lines.push('');

    lines.push(`  /**`);
    lines.push(`   * Decodes ScVal return value for function '${fn.name}'`);
    lines.push(`   */`);
    lines.push(`  public decode${capitalize(fn.name)}Result(scVal: xdr.ScVal): ${returnTsType} {`);
    lines.push(`    return ${generateScValDecoder(fn.outputs[0] || 'void')} as any;`);
    lines.push(`  }`);
    lines.push('');
  });

  lines.push(`}`);
  return lines.join('\n');
}

/**
 * Generates JSON metadata representation of the client generator output.
 */
export function generateJsonMetadata(spec: ParsedContractSpec, contractId: string): object {
  return {
    contractId,
    generatedMethodsCount: spec.functions.length,
    generatedTypesCount: spec.structs.length + spec.enums.length + spec.unions.length,
    methods: spec.functions.map((f) => ({
      name: f.name,
      signature: f.exampleSignature,
      argumentsCount: f.inputs.length,
    })),
  };
}

function capitalize(str: string): string {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Runs the Soroban contract client generator example.
 */
export async function run(params: ClientGeneratorParams = {}): Promise<void> {
  const contractId =
    params.contractId?.trim() ||
    process.env.CONTRACT_ID?.trim() ||
    'CDW6BR4A6MGGCW23SCAVBBBZ3HW4V5C3TJ35OC3D4RQ4A6MGGCW23SCA';

  console.log('Starting Soroban Contract Client Generation Example...');
  console.log(`Generating client for Contract ID: ${contractId}`);

  const entries = params.specData || getSampleSpecEntries();
  const parsedSpec = parseContractSpec(entries);

  const generatedCode = generateClientCode(parsedSpec, contractId);

  if (params.outputFilePath) {
    fs.writeFileSync(params.outputFilePath, generatedCode, 'utf-8');
    console.log(`Successfully written generated client code to file: ${params.outputFilePath}`);
  }

  if (params.jsonOutput || process.env.JSON_OUTPUT === 'true') {
    console.log(JSON.stringify(generateJsonMetadata(parsedSpec, contractId), null, 2));
  } else {
    console.log('\n=== Generated TypeScript Contract Client Source Code ===\n');
    console.log(generatedCode);
  }

  console.log('\nContract client generation completed successfully.');
}
